### PR TITLE
Add project configuration files

### PR DESCRIPTION
**Pull request by ifthenelse**
Add project configuration files and provide basic installation and bootstrapping steps.

### CODE REVIEW

**Review by ifthenelse — COMMENTED** [review]
All good ;-)

**Comment by ifthenelse** [comment]
Adding project configuration files.
I really would have used containers, but for some reason docker-compose is not working and it's too late to investigate.

**Comment by ifthenelse** [comment]
yes

**Review by ximes — APPROVED** [review]
It should be good to go but double check that no readme changes are overwritten and if we need to rebundle after the ruby version change. It looks to me like something got out of sync (e.g. the gemfile, it should have the version fixed too)

**Comment by ifthenelse** [comment]
@ximes already double checked, no info is lost in the manual merge. But for sure I'll toss the `gem install -g` step from `Readme.md`, since we're using bundler.

**Comment by ifthenelse** [comment]
As for the rebundle and config alignment, I did the following:
1. Run `gem uninstall -aIx`
2. Aligned ruby version to 3.2.1 in `Gemfile`
3. Run `bundle install`

Everything looks fine to me:
image
image

**Pull request merged**
